"""Admin credential reset for a forgotten password (single-user app).

Usage (inside the container):
    docker compose exec glucose-explorer python -m server.reset_password --request <code-from-login-page>
    docker compose exec glucose-explorer python -m server.reset_password            # direct reset (shell access = root of trust)
    docker compose exec glucose-explorer python -m server.reset_password --password 'new-password-here'
    docker compose exec glucose-explorer python -m server.reset_password --username newname

Prints the effective username and the new password — in this terminal only.
--request redeems a one-time code generated by the login page's "Forgot your
password?" link (valid 30 minutes, single use). Note: if APP_USERNAME is set
in .env it overrides the database username at login.
"""

import argparse
import hashlib
import json
import secrets
import sys
import time

from .auth import RESET_REQUEST_TTL, make_password_hash
from .config import env
from .db import get_setting, init_db, set_setting


def _redeem_request(code: str) -> None:
    raw = get_setting("reset_request")
    if not raw:
        sys.exit("No pending reset request. Generate one from the login page first.")
    try:
        req = json.loads(raw)
    except ValueError:
        sys.exit("Stored reset request is corrupt; generate a new one from the login page.")
    if int(time.time()) - int(req.get("ts", 0)) > RESET_REQUEST_TTL:
        sys.exit("Reset code expired (30 min limit). Generate a new one from the login page.")
    if hashlib.sha256(code.strip().encode()).hexdigest() != req.get("hash"):
        sys.exit("Reset code does not match the pending request.")
    set_setting("reset_request", "")  # single use


def main() -> None:
    parser = argparse.ArgumentParser(description="Reset the GlucoPilot admin password.")
    parser.add_argument("--password", help="New password (min 12 chars). Omit to generate a random one.")
    parser.add_argument("--username", help="Also set a new username in the database.")
    parser.add_argument("--request", help="One-time reset code generated by the login page.")
    args = parser.parse_args()

    password = args.password or secrets.token_urlsafe(12)
    if len(password) < 12:
        parser.error("Password must be at least 12 characters.")

    init_db()
    if args.request:
        _redeem_request(args.request)
    if args.username:
        set_setting("admin_username", args.username.strip())
    set_setting("admin_password_hash", make_password_hash(password))

    env_user = env("APP_USERNAME", "")
    db_user = get_setting("admin_username") or "admin"
    effective = env_user or db_user
    print(f"Username: {effective}" + (f"  (from APP_USERNAME in .env, overrides db value '{db_user}')" if env_user else ""))
    print(f"New password: {password}")
    if env("APP_PASSWORD_HASH", ""):
        print("WARNING: APP_PASSWORD_HASH is set in .env and overrides this reset — clear it and restart.")


if __name__ == "__main__":
    main()
